name: Feature Request
description: Request a Feature or Enhancement to the Package
title: "[Feature]: "
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              We're excited to hear you have an idea for a new feature. Can you help us understand it by providing the following details.
    - type: textarea
      id: what-feature
      attributes:
          label: What feature would you like to see?
          description: What is the feature you would like to see added to the package?
          placeholder: I would like to see a new feature that allows me to do X.
      validations:
          required: true
    - type: textarea
      id: why-feature
      attributes:
          label: Why do you need this feature?
          description: Why do you need this feature? What is the use case for it?
          placeholder: I need this feature because it would help me do X.
      validations:
          required: true
    - type: input
      id: package-version
      attributes:
          label: Package Version
          description: What version of our Package are you running? Please be as specific as possible
          placeholder: 1.x
      validations:
          required: true
    - type: input
      id: laravel-version
      attributes:
        label: Laravel Version
        description: What version of Laravel are you running? Please be as specific as possible
        placeholder: 10.x
      validations:
        required: true
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Is there anything else you can add to help us understand your feature request?
          placeholder: Tell us more about your feature request.
