name: Fix PHP code style issues

on:
  push:
    branches: [main]
    paths:
      - '**.php'

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prepare the branch
        run: |
          git branch -d fix-styling-issues || true
          git checkout -b fix-styling-issues

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.3.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling issues
          branch: fix-styling-issues

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Fix styling issues
          title: Fix styling issues
          reviewers: uutkukorkmaz
          delete-branch: true
          body: |
            This PR fixes the styling issues in the codebase.
          branch: fix-styling-issues
          base: main

